# Generated by Django 3.1.1 on 2020-09-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_course_patner_publication_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patner',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
