# Generated by Django 3.1.1 on 2020-09-16 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_webinar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webinar',
            old_name='link',
            new_name='youtube_link',
        ),
        migrations.AddField(
            model_name='webinar',
            name='zoom_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
