# Generated by Django 3.1.1 on 2020-10-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200916_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf',
            field=models.FileField(default=1, upload_to='blog-pdfs'),
            preserve_default=False,
        ),
    ]
